language: node_js
cache:
  directories:
  - vendor/bundle
  - bower_components
  - node_modules
node_js:
- 4.4.3
install: "./setup.sh"
script: npm run build
after_success: "./deploy.sh"
env:
  global:
  - secure: GySBQnXj/UDavfg9vx49vejjw81AvBAgZQqW4pKQix7aNUTXMS6YMGLyq4ZOf8yn0DttkIZ5DgWRtjfbCgJhbR4Vjor6EpUWeUq8f/ZU75JlcRbCXNV9m6tlyeQQTaerl2IObdZM9OyTxfyb1kKhnOD0DWHZFlDSOEnqpumTrp8=
